[package]
name = "wl-protocol"
version = "0.0.0"
authors = ["AidoP <aidop@me.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
toml = { version = "0.5" }
quick-xml = "0.21"
clap = "2.33"