name = 'input_method_unstable_v1'
copyright = '''
Copyright © 2012, 2013 Intel Corporation

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice (including the next
paragraph) shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.'''

[[interface]]
name = 'zwp_input_method_context_v1'
summary = 'input method context'
description = '''
Corresponds to a text input on the input method side. An input method context
is created on text input activation on the input method side. It allows
receiving information about the text input from the application via events.
Input method contexts do not keep state after deactivation and should be
destroyed after deactivation is handled.

Text is generally UTF-8 encoded, indices and lengths are in bytes.

Serials are used to synchronize the state between the text input and
an input method. New serials are sent by the text input in the
commit_state request and are used by the input method to indicate
the known text input state in events like preedit_string, commit_string,
and keysym. The text input can then ignore events from the input method
which are based on an outdated state (for example after a reset).

Warning! The protocol described in this file is experimental and
backward incompatible changes may be made. Backward compatible changes
may be added together with the corresponding interface version bump.
Backward incompatible changes are done by bumping the version number in
the protocol and interface names and resetting the interface version.
Once the protocol is to be declared stable, the 'z' prefix and the
version number in the protocol and interface names are removed and the
interface version number is reset.'''
version = 1

[[interface.request]]
name = 'destroy'
destructor = true

[[interface.request]]
name = 'commit_string'
summary = 'commit string'
description = '''
Send the commit string text for insertion to the application.

The text to commit could be either just a single character after a key
press or the result of some composing (pre-edit). It could be also an
empty text when some text should be removed (see
delete_surrounding_text) or when the input cursor should be moved (see
cursor_position).

Any previously set composing text will be removed.'''

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial of the latest known text input state'

[[interface.request.arg]]
name = 'text'
type = 'string'

[[interface.request]]
name = 'preedit_string'
summary = 'pre-edit string'
description = '''
Send the pre-edit string text to the application text input.

The commit text can be used to replace the pre-edit text on reset (for
example on unfocus).

Previously sent preedit_style and preedit_cursor requests are also
processed by the text_input.'''

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial of the latest known text input state'

[[interface.request.arg]]
name = 'text'
type = 'string'

[[interface.request.arg]]
name = 'commit'
type = 'string'

[[interface.request]]
name = 'preedit_styling'
summary = 'pre-edit styling'
description = '''
Set the styling information on composing text. The style is applied for
length in bytes from index relative to the beginning of
the composing text (as byte offset). Multiple styles can
be applied to a composing text.

This request should be sent before sending a preedit_string request.'''

[[interface.request.arg]]
name = 'index'
type = 'uint'

[[interface.request.arg]]
name = 'length'
type = 'uint'

[[interface.request.arg]]
name = 'style'
type = 'uint'

[[interface.request]]
name = 'preedit_cursor'
summary = 'pre-edit cursor'
description = '''
Set the cursor position inside the composing text (as byte offset)
relative to the start of the composing text.

When index is negative no cursor should be displayed.

This request should be sent before sending a preedit_string request.'''

[[interface.request.arg]]
name = 'index'
type = 'int'

[[interface.request]]
name = 'delete_surrounding_text'
summary = 'delete text'
description = '''
Remove the surrounding text.

This request will be handled on the text_input side directly following
a commit_string request.'''

[[interface.request.arg]]
name = 'index'
type = 'int'

[[interface.request.arg]]
name = 'length'
type = 'uint'

[[interface.request]]
name = 'cursor_position'
summary = 'set cursor to a new position'
description = '''
Set the cursor and anchor to a new position. Index is the new cursor
position in bytes (when >= 0 this is relative to the end of the inserted text,
otherwise it is relative to the beginning of the inserted text). Anchor is
the new anchor position in bytes (when >= 0 this is relative to the end of the
inserted text, otherwise it is relative to the beginning of the inserted
text). When there should be no selected text, anchor should be the same
as index.

This request will be handled on the text_input side directly following
a commit_string request.'''

[[interface.request.arg]]
name = 'index'
type = 'int'

[[interface.request.arg]]
name = 'anchor'
type = 'int'

[[interface.request]]
name = 'modifiers_map'

[[interface.request.arg]]
name = 'map'
type = 'array'

[[interface.request]]
name = 'keysym'
summary = 'keysym'
description = '''
Notify when a key event was sent. Key events should not be used for
normal text input operations, which should be done with commit_string,
delete_surrounding_text, etc. The key event follows the wl_keyboard key
event convention. Sym is an XKB keysym, state is a wl_keyboard key_state.'''

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial of the latest known text input state'

[[interface.request.arg]]
name = 'time'
type = 'uint'

[[interface.request.arg]]
name = 'sym'
type = 'uint'

[[interface.request.arg]]
name = 'state'
type = 'uint'

[[interface.request.arg]]
name = 'modifiers'
type = 'uint'

[[interface.request]]
name = 'grab_keyboard'
summary = 'grab hardware keyboard'
description = '''
Allow an input method to receive hardware keyboard input and process
key events to generate text events (with pre-edit) over the wire. This
allows input methods which compose multiple key events for inputting
text like it is done for CJK languages.'''

[[interface.request.arg]]
name = 'keyboard'
type = 'new_id'
interface = 'wl_keyboard'

[[interface.request]]
name = 'key'
summary = 'forward key event'
description = '''
Forward a wl_keyboard::key event to the client that was not processed
by the input method itself. Should be used when filtering key events
with grab_keyboard. The arguments should be the ones from the
wl_keyboard::key event.

For generating custom key events use the keysym request instead.'''

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial from wl_keyboard::key'

[[interface.request.arg]]
name = 'time'
type = 'uint'
summary = 'time from wl_keyboard::key'

[[interface.request.arg]]
name = 'key'
type = 'uint'
summary = 'key from wl_keyboard::key'

[[interface.request.arg]]
name = 'state'
type = 'uint'
summary = 'state from wl_keyboard::key'

[[interface.request]]
name = 'modifiers'
summary = 'forward modifiers event'
description = '''
Forward a wl_keyboard::modifiers event to the client that was not
processed by the input method itself. Should be used when filtering
key events with grab_keyboard. The arguments should be the ones
from the wl_keyboard::modifiers event.'''

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial from wl_keyboard::modifiers'

[[interface.request.arg]]
name = 'mods_depressed'
type = 'uint'
summary = 'mods_depressed from wl_keyboard::modifiers'

[[interface.request.arg]]
name = 'mods_latched'
type = 'uint'
summary = 'mods_latched from wl_keyboard::modifiers'

[[interface.request.arg]]
name = 'mods_locked'
type = 'uint'
summary = 'mods_locked from wl_keyboard::modifiers'

[[interface.request.arg]]
name = 'group'
type = 'uint'
summary = 'group from wl_keyboard::modifiers'

[[interface.request]]
name = 'language'

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial of the latest known text input state'

[[interface.request.arg]]
name = 'language'
type = 'string'

[[interface.request]]
name = 'text_direction'

[[interface.request.arg]]
name = 'serial'
type = 'uint'
summary = 'serial of the latest known text input state'

[[interface.request.arg]]
name = 'direction'
type = 'uint'

[[interface.event]]
name = 'surrounding_text'
summary = 'surrounding text event'
description = '''
The plain surrounding text around the input position. Cursor is the
position in bytes within the surrounding text relative to the beginning
of the text. Anchor is the position in bytes of the selection anchor
within the surrounding text relative to the beginning of the text. If
there is no selected text then anchor is the same as cursor.'''

[[interface.event.arg]]
name = 'text'
type = 'string'

[[interface.event.arg]]
name = 'cursor'
type = 'uint'

[[interface.event.arg]]
name = 'anchor'
type = 'uint'

[[interface.event]]
name = 'reset'

[[interface.event]]
name = 'content_type'

[[interface.event.arg]]
name = 'hint'
type = 'uint'

[[interface.event.arg]]
name = 'purpose'
type = 'uint'

[[interface.event]]
name = 'invoke_action'

[[interface.event.arg]]
name = 'button'
type = 'uint'

[[interface.event.arg]]
name = 'index'
type = 'uint'

[[interface.event]]
name = 'commit_state'

[[interface.event.arg]]
name = 'serial'
type = 'uint'
summary = 'serial of text input state'

[[interface.event]]
name = 'preferred_language'

[[interface.event.arg]]
name = 'language'
type = 'string'

[[interface]]
name = 'zwp_input_method_v1'
summary = 'input method'
description = '''
An input method object is responsible for composing text in response to
input from hardware or virtual keyboards. There is one input method
object per seat. On activate there is a new input method context object
created which allows the input method to communicate with the text input.'''
version = 1

[[interface.event]]
name = 'activate'
summary = 'activate event'
description = '''
A text input was activated. Creates an input method context object
which allows communication with the text input.'''

[[interface.event.arg]]
name = 'id'
type = 'new_id'
interface = 'zwp_input_method_context_v1'

[[interface.event]]
name = 'deactivate'
summary = 'deactivate event'
description = '''
The text input corresponding to the context argument was deactivated.
The input method context should be destroyed after deactivation is
handled.'''

[[interface.event.arg]]
name = 'context'
type = 'object'
interface = 'zwp_input_method_context_v1'

[[interface]]
name = 'zwp_input_panel_v1'
summary = 'interface for implementing keyboards'
description = 'Only one client can bind this interface at a time.'
version = 1

[[interface.request]]
name = 'get_input_panel_surface'

[[interface.request.arg]]
name = 'id'
type = 'new_id'
interface = 'zwp_input_panel_surface_v1'

[[interface.request.arg]]
name = 'surface'
type = 'object'
interface = 'wl_surface'

[[interface]]
name = 'zwp_input_panel_surface_v1'
version = 1

[[interface.enum]]
name = 'position'

[[interface.enum.entry]]
name = 'center_bottom'
value = 0

[[interface.request]]
name = 'set_toplevel'
summary = 'set the surface type as a keyboard'
description = '''
Set the input_panel_surface type to keyboard.

A keyboard surface is only shown when a text input is active.'''

[[interface.request.arg]]
name = 'output'
type = 'object'
interface = 'wl_output'

[[interface.request.arg]]
name = 'position'
type = 'uint'

[[interface.request]]
name = 'set_overlay_panel'
summary = 'set the surface type as an overlay panel'
description = '''
Set the input_panel_surface to be an overlay panel.

This is shown near the input cursor above the application window when
a text input is active.'''
